# Generated by Django 4.2.1 on 2023-05-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_projects_projectlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
